### ISSUE TITLE
Issue with my filters - Cannot determine the module for the class RegionFilter

### ISSUE THREAD

**Issue by markoddi01** [dfaglioni/angular-seed-lazy-aot#12]
@netstart @dfaglioni  Issue with my filters - Cannot determine the module for the class RegionFilter.

I get this error when I do **npm run serve.prod**

I have this with all my filters.

**This is the region filter**:
```

import { Pipe } from "@angular/core";

@Pipe({
	name: 'regionFilter',
  pure: true
})

export class RegionFilter {
   transform(items: any, [originalListOfItems, region]: any) {
  	  //Default get variables:   
        var filterByRegion = false;
        var overallResults = items;

      //Set default filters:
        if (region !== "Filter by Region") {
          filterByRegion = true; 
          overallResults = originalListOfItems;
        } 
      
      //Filter options:
        if (filterByRegion)
            overallResults = overallResults.filter(item =>  item.region === region);

        return overallResults;
  }
}

```

This is the git bash with the region error:

![image](https://cloud.githubusercontent.com/assets/2556223/21907414/652418ae-d907-11e6-8937-c5cb884ac552.png)

**Comment by netstart** [comment]
1 - Never use jquery with angular.
2 - Need declare ou pipe in one @NgModule, try add in you AppModule

**Comment by markoddi01** [comment]
That seemed to work. Thanks (Still got 68 issues to get this app running)
