### ISSUE TITLE
When running npm run start I get Firebase typings error

### ISSUE THREAD

**Issue by markoddi01** [dfaglioni/angular-seed-lazy-aot#6]
I cloned the app, did npm install and then did npm run start etc and all worked fine.

I did npm run serve.prod and got git bash issues.

I haven't merged my code in yet. I just wanted to see if it works with dummy app.

@dfaglioni did you have the same problem?

This is the screen shot:

![image](https://cloud.githubusercontent.com/assets/2556223/21741597/188f6c38-d4d3-11e6-828c-8cbf267f9ae1.png)

**Comment by dfaglioni** [comment]
@markoddi01 
Hi Mark, the problem only occurs on windows because of the single quotes. I guess  it's corrected now, can you try again?

**Comment by markoddi01** [comment]
Ok thanks. I will try it again tonight

**Comment by markoddi01** [comment]
Do I just pull the master branch?

**Comment by anderson-custodio** [comment]
@markoddi01 yeah man!

**Comment by markoddi01** [comment]
@afcustodioo and @dfaglioni the serve.prod works now. Thank you and I've managed to build the dist folder.

How do I run the dist app? 

Second question I've done an build now with my app in and it doesnt like that I use Firebase.
I have firebase lib in my index.html page point to the lib for firebase.

This is my git bash error:

![image](https://cloud.githubusercontent.com/assets/2556223/21863053/c137c8ea-d833-11e6-9548-7c884b630b2b.png)

**Comment by netstart** [comment]
In the seed https://github.com/mgechev/angular-seed you will reference html temple without ./ in initial
like this: https://github.com/mgechev/angular-seed/blob/master/src/client/app/home/home.component.ts

@Component({
  moduleId: module.id,
  selector: 'sd-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css'],
})
export class HomeComponent implements OnInit {}

But in our seed, you will write like this: https://github.com/Elotech-Dev/angular-seed-lazy-aot/blob/master/src/app/app.component.ts

@Component({
  selector: 'sd-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {}
