### ISSUE TITLE
When running npm run start I get an issue with moment js and firebase plugins

### ISSUE THREAD

**Issue by markoddi01** [dfaglioni/angular-seed-lazy-aot#8]
@netstart @dfaglioni When running npm run start I get an issue with moment js plugin.

This is my tsconfig (I added firebase and moment types but doesn't seem to have worked):

```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "isolatedModules": true,
    "typeRoots": [
      "../node_modules/@types",
      "../typings/index.d.ts"
    ],
    "types": [
      "node",
      "jasmine",
      "protractor",
      "firebase",
      "moment"
    ]
  }
}

```

**Error: cannot find moment.**

![image](https://cloud.githubusercontent.com/assets/2556223/21866452/3c1347c0-d842-11e6-9bc1-91d199949f49.png)

This is my project config with them in:

import { join } from 'path';
import { SeedConfig } from './seed.config';

export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();

    this.SCRIPTS = [ 
      '../src/resources/firebase.js',
      '../src/resources/moment.js'
    ];

    this.STYLES = [
      //  '../node_modules/bootstrap/dist/css/bootstrap.css'
    ];

    this.ASSETS = [ ...this.ASSETS
      //  '../node_modules/bootstrap/dist/css/bootstrap.css'
    ];

  }

}

**Comment by netstart** [comment]
Please, Can you show me your full code?
We need a full code to analyse!


What is moment? I supose is your variable. Am I correct?

**Comment by markoddi01** [comment]
@netstart I have moment js which is a plugin I need for date time. Firebase I use for the database.

Both those keywords are causing build issues as it doesnt recognise them.

I think I need to add there typings and reference them to the app somehow.

I'm not too sure how?

What files would you like to see?

This is my folder structure:

![image](https://cloud.githubusercontent.com/assets/2556223/21904096/6a8825f4-d8fa-11e6-9bee-61d894238210.png)


Thank you for your help so far

**Comment by markoddi01** [comment]
I've tried this: npm install --save-dev @types/firebase

add "types": ["firebase"] on tsconfig.json at src/client.

**Comment by markoddi01** [comment]
@netstart I've added the typings for moment and firebase but I still get the same error.

Below is my files:

![bugs](https://cloud.githubusercontent.com/assets/2556223/21906083/bae8bb56-d901-11e6-97df-0603e81e7501.png)

This is my git bash running with npm run start (Lots of Firebase errors (I'm not sure why?)):

![image](https://cloud.githubusercontent.com/assets/2556223/21906100/d127a21a-d901-11e6-964b-d5184b359987.png)

**Comment by netstart** [comment]
The base of this  seed is angular-cli, so, you need modify angular-cli.json


look global library instalation in
https://github.com/angular/angular-cli#global-library-installation

look 3rd party libray installation to
https://github.com/angular/angular-cli#3rd-party-library-installation

If  this resolve this problem, please, close  this issue
